version: "3.7"

volumes:
  portainer_data:

networks:
  workspace_network:
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: ${IP_NETWORK}

services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer
    networks:
      workspace_network:
        ipv4_address: ${IP_PORTAINER}
    ports:
      - "${PORTAINER_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:${MARIADB_VERSION}
    networks:
      workspace_network:
        ipv4_address: ${IP_MARIADB}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - "${MYSQL_PORT}:3306"

  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      workspace_network:
        ipv4_address: ${IP_PHP_MYADMIN}
    environment:
      MYSQL_USERNAME: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    volumes:
      - "/sessions"
    links:
      - "mariadb:db"

  maildev:
    container_name: maildev
    hostname: maildev
    image: djfarrelly/maildev
    networks:
      workspace_network:
        ipv4_address: ${IP_MAILDEV}
    ports:
      - "${SMTP_PORT}:25"
      - "${WEBUI_PORT}:80"