version: "3.7"

volumes:
  portainer_data:

networks:
  workspace_network:
    external:
      name: docker-workspace_workspace_network

services:
  php-fpm:
    container_name: ${PREFIX}php_${PHP_VERSION}
    hostname: ${PREFIX}php_${PHP_VERSION}
    networks:
      workspace_network:
        ipv4_address: ${IP_PHP_FPM}
    build:
      context: ./php_${SGBD}_container
      dockerfile: Dockerfile
      args:
        php_version: ${PHP_VERSION}
    volumes:
      - /home/${MYUSER}/source_code/${PROJECT}:/var/www

  nginx:
    container_name: ${PREFIX}nginx
    hostname: ${PREFIX}nginx
    ports:
      - "${HTTP}:80"
      - "${HTTPS}:443"
    networks:
      workspace_network:
        ipv4_address: ${IP_NGINX}
    build:
      context: .
      dockerfile: ./nginx_container/Dockerfile
      args:
        myuser: ${MYUSER}
        php_version: ${PHP_VERSION}
        node_version: ${NODE_VERSION}
        nginx_version: ${NGINX_VERSION}
        ubuntu_version: ${UBUNTU_VERSION}
    volumes:
      - /home/${MYUSER}/source_code/${PROJECT}:/var/www
      - /home/${MYUSER}/${VOLUME}/${PROJECT}_nginx:/var/log/nginx
    links:
      - php-fpm:phpfpm
